"""create initial tables

Revision ID: f49b347a5577
Revises: 
Create Date: 2025-07-09 21:39:21.238119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49b347a5577'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shelf_life', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('last_available', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True),
    sa.CheckConstraint("meal_type IN ('pre-breakfast', 'breakfast', 'lunch', 'dinner', 'snack', 'weekend prep', 'sides')", name='recipes_meal_type_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('recipe_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.CheckConstraint("meal_type IN ('pre-breakfast', 'breakfast', 'lunch', 'dinner', 'snack')", name='weekly_plan_meal_type_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'meal_type', name='unique_day_meal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_plan')
    op.drop_table('recipes')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
